lidarmultinet_ohem_nogcp_remove_outside.pth:
	scp xrhuang@sonata.csail.mit.edu:/mnt2/xrhuang/openpcdet/checkpoints/$@ ./

lidarmultinet_ohem_remove_outside.pth:
	scp xrhuang@sonata.csail.mit.edu:/mnt2/xrhuang/openpcdet/checkpoints/$@ ./

volumeconvnet_remove_outside.pth:
	scp xrhuang@sonata.csail.mit.edu:/mnt2/xrhuang/openpcdet/checkpoints/$@ ./

pointconvnet_from_lidarmultinet.pth:
	scp xrhuang@sonata.csail.mit.edu:/mnt2/xrhuang/openpcdet/checkpoints/$@ ./

pointconvnet.pth:
	scp xrhuang@sonata.csail.mit.edu:/mnt2/xrhuang/openpcdet/checkpoints/$@ ./
	
pointconvnet_remove_outside_empty.pth:
	scp xrhuang@sonata.csail.mit.edu:/mnt2/xrhuang/openpcdet/checkpoints/$@ ./

pointconvnet_remove_outside_from_lidarmultinet.pth:
	scp xrhuang@sonata.csail.mit.edu:/mnt2/xrhuang/openpcdet/checkpoints/$@ ./

